# Generated by Django 3.2.6 on 2021-08-09 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_gradecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('your_image', models.ImageField(upload_to='images/')),
                ('video', models.FileField(upload_to='videos/')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.grade')),
            ],
        ),
    ]
